version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - DEFAULT_MODEL_NAME=${DEFAULT_MODEL_NAME}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    ports:
      - "3012:3000"
